imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache:                         apc
#
#doctrine:
#    orm:
#        entity_managers:
#            default:
#                metadata_cache_driver: apc
#                query_cache_driver:    apc
#                result_cache_driver:   apc

monolog:
    handlers:
        main:
            type:         stream
            path:         %kernel.logs_dir%/%kernel.name%_%kernel.environment%.log
            level:        info
